### ISSUE TITLE
USER STORY: Navigation Bar

### ISSUE THREAD

**Issue by cornishcoder1** [cornishcoder1/pp5-frontend-the-winding-path#1]
As a user I can view the navigation bar on every page so that I can navigate easily around the application. 

## Acceptance Criteria

* Navigation bar is visible on every page 
* Navigation contains links to Home, Sign In and Sign Up for new users
* Navigation contains links to Add Post, Home, Following, Saved Posts, Sign Out and Profile for registered users
  
## Tasks
  
 - [ ] Create and style navbar
 - [ ] Add relevant links to each navbar (new and registered users)
 - [ ] Wire up links
