### ISSUE TITLE
USER STORY: View posts and comments in date order (descending)

### ISSUE THREAD

**Issue by cornishcoder1** [cornishcoder1/pp5-frontend-the-winding-path#11]
As a user I can view all posts and comments in date order (descending) so that I can quickly see the most recent content

## Acceptance Criteria

 - [x] Posts display in date order
 - [x] Comments display in date order
  
## Tasks
  
 - [x] Add [-updated on]
