### ISSUE TITLE
USER STORY: Search posts (walk)

### ISSUE THREAD

**Issue by cornishcoder1** [cornishcoder1/pp5-frontend-the-winding-path#12]
As a user I can search for walk posts by owner, title, environment or difficulty so that I can find the content I am most interested in.

## Acceptance Criteria

 - [x] Search bar is available on home, following and saved walks pages
 - [x] Search bar returns results filtered by keywords from owner, title, environment or difficulty data
  
## Tasks
  
 - [x] Add search bar to all feed pages
 - [x] Filter results by relevant data

**Comment by cornishcoder1** [comment]
Still need to add 'Following' feed and search bar
