### ISSUE TITLE
USER STORY: View gallery post likes

### ISSUE THREAD

**Issue by cornishcoder1** [cornishcoder1/pp5-frontend-the-winding-path#14]
As a user I can see how many likes a gallery post has had so that I can gauge it’s popularity. 

## Acceptance Criteria

 - [x] Like count is visible on each gallery post
 - [x] Like count will increase/decrease according to number of likes/unlikes
  
## Tasks
  
 - [x] Render likes count on a gallery post
