### ISSUE TITLE
USER STORY: Delete comment

### ISSUE THREAD

**Issue by cornishcoder1** [cornishcoder1/pp5-frontend-the-winding-path#19]
As a user I can delete my own comments so that I can remove comments that I no longer want on the application.

## Acceptance Criteria

 - [x] A dropdown menu will be available to the user on their own comments in the comment list
 - [x] The user can click 'delete' in the dropdown menu to delete the comment

## Tasks
  
 - [x] Add delete button to comment dropdown menu
 - [x] Write handleDelete functions for gallery and walk post comments
