### ISSUE TITLE
USER STORY: Create post (gallery)

### ISSUE THREAD

**Issue by cornishcoder1** [cornishcoder1/pp5-frontend-the-winding-path#2]
As a user I can add gallery posts so that I can share my artwork or photography with other users. 

## Acceptance Criteria

 - [x] User can access a 'Create Gallery Post' form via a link on the Gallery Page
 - [x] Upon submission, form data is sent to the DRF API 
 - [x] Gallery Post displays on Gallery page feed with all form data present
  
## Tasks
  
 - [x] Create gallery post form
