### ISSUE TITLE
USER STORY: Follow profiles

### ISSUE THREAD

**Issue by cornishcoder1** [cornishcoder1/pp5-frontend-the-winding-path#20]
As a user I can follow and unfollow profiles that are of particular interest, so that I can find the relevant content again later in my ‘Following’ feed. 

## Acceptance Criteria

 - [x] A list of user profiles is available on the home page, with a follow/unfollow for each of them
 - [x] Users are able to 'follow' a fellow user's profile, and have that user's walk post display in their 'Following' feed
  
## Tasks
  
 - [x] Add list of profiles to home page with follow/unfollow button
