### ISSUE TITLE
USER STORY: Following feed

### ISSUE THREAD

**Issue by cornishcoder1** [cornishcoder1/pp5-frontend-the-winding-path#21]
As a user I can access a ‘Following’ feed , so that I can view content filtered by what profiles I follow.

## Acceptance Criteria

 - [x] Following feed/page is accessible from navigation bar
 - [x] Following feed shows walk posts filtered by profiles the user is following
  
## Tasks
  
 - [x] Add link to 'Following' feed in navigation bar
 - [x] Ensure only posts filtered by profiles the user is following show in this feed
