### ISSUE TITLE
USER STORY: 'Who to follow' list

### ISSUE THREAD

**Issue by cornishcoder1** [cornishcoder1/pp5-frontend-the-winding-path#24]
As a user I can access a list of ‘Who to Follow’ profiles so that I can see and interact with other users of the site and their content.

## Acceptance Criteria

 - [x] A list of 'Who to follow' will be displayed on the home, following and saved walks pages
 - [x] The list will contain user profile names and avatars
 - [x] Users can click a follow/unfollow button
  
## Tasks
  
 - [x] Build Profiles component
 - [x] Display on relevant pages
