### ISSUE TITLE
USER STORY: Access profiles of other users

### ISSUE THREAD

**Issue by cornishcoder1** [cornishcoder1/pp5-frontend-the-winding-path#25]
As a user I can access other users profiles so that I can view walk posts by a specific user. 

## Acceptance Criteria

 - [x] Users can click into profiles and view that user's walk posts. 
  
## Tasks
  
 - [x] Profiles can be accessed via profile name/avatar
 - [x] Render walk post list in the relevant user's profile
