### ISSUE TITLE
USER STORY: View user stats

### ISSUE THREAD

**Issue by cornishcoder1** [cornishcoder1/pp5-frontend-the-winding-path#26]
As a user I can view stats on user profiles so that I can learn more about a specific user. 

## Acceptance Criteria

 - [x] Follower/Following count is displayed in the user profile
 - [x] Post count is displayed in the user profile

  
## Tasks
  
 - [x] Add relevant count data to Profile page
