### ISSUE TITLE
USER STORY: Change password

### ISSUE THREAD

**Issue by cornishcoder1** [cornishcoder1/pp5-frontend-the-winding-path#28]
As a user I can change my password so that I can ensure security if required.

## Acceptance Criteria

 - [x] A dropdown menu is available to a user on their profile, this will include option to change password
  
## Tasks
  
 - [x] Add change password option to user profile dropdown menu
 - [x] Link to a form which allows password to be changed
