### ISSUE TITLE
USER STORY: Change username

### ISSUE THREAD

**Issue by cornishcoder1** [cornishcoder1/pp5-frontend-the-winding-path#29]
As a user I can change my username so that I can ensure security if required.

## Acceptance Criteria

 - [x] A dropdown menu is available to a user on their profile, this will include option to change username
  
## Tasks
  
 - [x] Add change username option to user profile dropdown menu
 - [x] Link to a form which allows username to be changed
