### ISSUE TITLE
USER STORY: Navigation bar

### ISSUE THREAD

**Issue by cornishcoder1** [cornishcoder1/pp5-frontend-the-winding-path#3]
As a user I can view the navigation bar on every page so that I can navigate easily around the application. 

## Acceptance Criteria

 - [x] Nav bar displays at the top of all pages
 - [x] Nav bar displays different icons/links depending on whether a user is logged in or logged out
 - [x] All links work and take the user to the correct url
 - [x] Hamburger menu present and working on screen sizes medium and below
  
## Tasks
  
 - [x] Create icons/links for logged out users
 - [x] Create icons/links for logged in users
 - [x] Ensure hamburger menu displays for smaller screen sizes
