### ISSUE TITLE
USER STORY: Contact form

### ISSUE THREAD

**Issue by cornishcoder1** [cornishcoder1/pp5-frontend-the-winding-path#30]
As a user I can fill out and submit a contact form so that I can make admin aware of any issues or feedback

## Acceptance Criteria

* Link to contact form is available in navigation bar
* Form can be filled in and submitted to DRF
* Form is accessible in admin area of DRF
  
## Tasks
  
 - [x] Create contact form
 - [x] Add link to Contact Us form in navigation bar
 - [x] Add re-direct to confirmation page upon successful submission of form
