### ISSUE TITLE
USER STORY : Read post (walk)

### ISSUE THREAD

**Issue by cornishcoder1** [cornishcoder1/pp5-frontend-the-winding-path#34]
As a user I can read a walk post so that I have access to all the information within that post

## Acceptance Criteria

 - [x] Users can click into a walk post and view all information 
 - [x] Users can read a walk post's comment list and access the comment form within the walk post page
  
## Tasks
  
 - [x] Create a post page 
 - [x] Add comment form and list to post page
