### ISSUE TITLE
USER STORY: Read post (gallery)

### ISSUE THREAD

**Issue by cornishcoder1** [cornishcoder1/pp5-frontend-the-winding-path#35]
As a user I can read a gallery post so that I have access to all the information within that post

## Acceptance Criteria

 - [x] Users can click into a gallery post and view all information 
 - [x] Users can read a gallery post's comment list and access the comment form within the gallery post page
  
## Tasks
  
 - [x] Create a post page 
 - [x] Add comment form and list to post page
