### ISSUE TITLE
USER STORY: About page

### ISSUE THREAD

**Issue by cornishcoder1** [cornishcoder1/pp5-frontend-the-winding-path#36]
As a user I can access an 'about' page so that I can find out more about the application.

## Acceptance Criteria

 - [x] An about page is accessible from the navigation bar
 - [x] The about page gives some information about the purpose of the application

  
## Tasks
  
 - [x] Create 'About Page' with information about the application 
 - [x] Link to page in navigation bar
