### ISSUE TITLE
USER STORY: Search posts (gallery)

### ISSUE THREAD

**Issue by cornishcoder1** [cornishcoder1/pp5-frontend-the-winding-path#37]
As a user I can search for gallery posts by owner or title so that I can find the content I am most interested in.

## Acceptance Criteria

 - [x] Search bar is available on gallery page
 - [x] Search bar returns results filtered by keywords from owner or title data
  
## Tasks
  
 - [x] Add search bar to all feed pages
 - [x] Filter results by relevant data
