### ISSUE TITLE
USER STORY: Sign up

### ISSUE THREAD

**Issue by cornishcoder1** [cornishcoder1/pp5-frontend-the-winding-path#4]
As a user I can access the Sign Up option so that I can create an account and access all features available to signed up users.

## Acceptance Criteria

 - [x] Link to Sign Up form present in navbar
 - [x] Once a user is signed up, they are re-directed to the log in page
 - [x] A user account/profile is created in the DRF API
  
## Tasks
  
 - [x] Create Sign Up page with form
 - [x] Add Sign Up link to nav bar
 - [x] Ensure sign up data is posted to the API
