### ISSUE TITLE
USER STORY: Log in

### ISSUE THREAD

**Issue by cornishcoder1** [cornishcoder1/pp5-frontend-the-winding-path#5]
As a user I can log in with my authentication credentials so that I can access all features available to signed up users.

## Acceptance Criteria

 - [x] Link to Log In form present in navigation bar
 - [x] Upon logging in, all functionality is available to logged in user
  
## Tasks
  
 - [x]  Create Log in page with form
 - [x]  Add Log in link to nav bar
