### ISSUE TITLE
USER STORY: Authentication status

### ISSUE THREAD

**Issue by cornishcoder1** [cornishcoder1/pp5-frontend-the-winding-path#6]
As a user I can see my authentication status so that I know whether or not I need to log in. 

## Acceptance Criteria

 - [x] Navbar will display log in/log out links depending on status
 - [x] User's avatar and username will display in navigation bar if user is logged in
 - [x]  Avatar/Username will link to profile of logged in user 
  
## Tasks
  
 - [x] Add avatar and like to Profile to logged in navbar
