### ISSUE TITLE
USER STORY: Log out

### ISSUE THREAD

**Issue by cornishcoder1** [cornishcoder1/pp5-frontend-the-winding-path#7]
As a (logged in) user I can access the log out option in the navbar so that I can log out of my account.  

## Acceptance Criteria

 - [x] Link to Log Out displays in navbar if user is logged in 
 - [x] Clicking link logs user out
  
## Tasks
  
 - [x] Add Log Out link to logged in nav bar
